services:
  app:
    build: .
    container_name: django-container
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django-image
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db  # Optional but clarifies the hostname
      - DB_PORT=5432
    container_name: postgres-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

