services:
  app:
    build: .
    container_name: django-container
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django-image
    command: python manage.py runserver 0.0.0.0:8000